version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
